name = "Sympoly"
uuid = "0e2d26dc-53d7-47aa-8946-d9915dfd864d"
authors = ["Karl Royen <wessel.karl@googlemail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DiffRules = "b552c78f-8df3-52c6-915a-8e097449b14b"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[compat]
Combinatorics = "1.0.2"
DiffRules = "1.15.1"
Oscar = "1.3.0"
SymbolicUtils = "3.5.0"
TermInterface = "2.0.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
